// Generated by CoffeeScript 1.6.2
(function() {
  var List, test, test2;

  List = (function() {
    function List(array) {
      this.array = array != null ? array : [];
    }

    List.prototype.remove = function(element) {
      var t, _ref;

      if (element ? (t = this.array.indexOf(element)) > -1 : void 0) {
        return ([].splice.apply(this.array, [t, t - t + 1].concat(_ref = [])), _ref);
      }
    };

    List.prototype.add = function(element) {
      return this.array.push(element);
    };

    List.prototype.values = function() {
      return this.array;
    };

    return List;

  })();

  test = new List();

  test.add(1);

  test.add(2);

  test2 = new List();

  test2.add(3);

  test2.add(4);

  console.log(test.values());

  console.log(test2.values());

  test2.add(5);

  console.log(test2.values());

  test2.remove(3);

  console.log(test2.values());

}).call(this);
